<script src="{{ url('js') }}/jquery-3.2.1.min.js"></script>
    <script src="{{ url('js') }}/pre-loader.js"> </script>
    <script src="{{ url('assets') }}/bootstrap/js/popper.min.js"></script>
    <script src="{{ url('assets') }}/bootstrap/js/bootstrap.min.js"></script>
    <script src="{{ url('assets') }}/bootstrap/js/bootstrap-select.min.js"></script>
    <script src="{{ url('assets') }}/font-size/js/rv-jquery-fontsize-2.0.3.js"></script>
    <script src="{{ url('js') }}/parallaxie.js"></script>
    <script src="{{ url('js') }}/TweenMax.min.js"></script>
    <script src="{{ url('js') }}/anchor.js"></script>
    <script src="{{ url('assets') }}/wow/wow.min.js"></script>
    <script src="{{ url('assets') }}/prism/prism.js"></script>
    <script src="{{ url('assets') }}/mailchimp/plugins.js"></script>
    <script src="{{ url('assets') }}/niceselectpicker/jquery.nice-select.min.js"></script>
    <script src="{{ url('assets') }}/mcustomscrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="{{ url('js') }}/main.js"></script>